version: 0.2

phases:
  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package \
        --s3-bucket $S3_BUCKET \
        --output-template-file packaged.yml

artifacts:
  files:
    - packaged.yml